#!/bin/bash
#Hey I am coding, while listening to weval :D
command=$1
    
PROJECT_NAME="$(pwd | grep -o '[^/]*$')"

mkdir -p .logs

run_nvim() {
    echo "Creating json file for nvim lsp"
    cmake -DCMAKE_EXPORT_COMPILE_COMMANDS=1 .
}

if [ "$command" = "build" ];
then
    make -C build -j$(nproc) 

elif [ "$command" = "run" ];
then
    "build/$PROJECT_NAME" "${@:2}"

elif [ "$command" = "--f-nvim" ];
then
    run_nvim
else
    echo "Set up script and build/run commands"
    sleep 1
    echo "Running cmake..."
    cmake -B build -S . "${@:1}"
    sleep 1
    if ! test -f "./compile_commands.json";
    then
        run_nvim     
    fi
fi
